<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXa4fYke\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXa4fYke/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXa4fYke.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXa4fYke\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXa4fYke\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xa4fYke',
    'container.build_id' => 'f6735697',
    'container.build_time' => 1618451215,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXa4fYke');
