<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHJzvhC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHJzvhC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHJzvhC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHJzvhC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXHJzvhC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XHJzvhC',
    'container.build_id' => '3a4b3abd',
    'container.build_time' => 1619057884,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHJzvhC');
