<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA7m1aiK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA7m1aiK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA7m1aiK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA7m1aiK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA7m1aiK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A7m1aiK',
    'container.build_id' => '193f4010',
    'container.build_time' => 1619149328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA7m1aiK');
